AWSTemplateFormatVersion: '2010-09-09'
Description: 'TTLeague Players - Frontend Infrastructure (S3 + CloudFront)'

Parameters:
  Environment:
    Type: String
    AllowedValues: [staging, prod]
    Description: Environment name
  
  DomainName:
    Type: String
    Description: Frontend domain name (e.g., staging.ttleagueplayers.uk)
  
  CertificateArn:
    Type: String
    Description: ACM Certificate ARN in us-east-1 for CloudFront

Conditions:
  IsProdOrStaging: !Or [!Equals [!Ref Environment, staging], !Equals [!Ref Environment, prod]]

Resources:
  # S3 Bucket for static website hosting
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: TTLeaguePlayers

  # Bucket Policy for public read access
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${FrontendBucket.Arn}/*'

  # CloudFront Origin Access Identity (for private S3 access - optional, using public for simplicity)
  # CloudFrontOAI:
  #   Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  #   Properties:
  #     CloudFrontOriginAccessIdentityConfig:
  #       Comment: !Sub 'OAI for ${DomainName}'

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Condition: IsProdOrStaging
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'TTLeague Players ${Environment} Frontend'
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            # For website endpoint (public access):
            # DomainName: !Sub '${DomainName}.s3-website.${AWS::Region}.amazonaws.com'
            # CustomOriginConfig:
            #   OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
        # Custom error responses for SPA routing
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        PriceClass: PriceClass_100
        HttpVersion: http2
        IPV6Enabled: true

Outputs:
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub 'ttleague-frontend-${Environment}-BucketName'
  
  BucketWebsiteURL:
    Description: S3 Website URL
    Value: !GetAtt FrontendBucket.WebsiteURL
    Export:
      Name: !Sub 'ttleague-frontend-${Environment}-WebsiteURL'
  
  CloudFrontDomainName:
    Condition: IsProdOrStaging
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub 'ttleague-frontend-${Environment}-CloudFrontDomain'
  
  CloudFrontDistributionId:
    Condition: IsProdOrStaging
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub 'ttleague-frontend-${Environment}-DistributionId'
  
  FrontendURL:
    Condition: IsProdOrStaging
    Description: Frontend URL
    Value: !Sub 'https://${DomainName}'
    Export:
      Name: !Sub 'ttleague-frontend-${Environment}-URL'
