AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
#    Default: dev   # this force all the commands to specify the environments and avoids confusions caused by mixing the architectures
    AllowedValues: [dev, test, staging, prod]

  # NOTE: These are primarily for local dev (SAM) vs cloud deploy differences.
  # In AWS you can choose either architecture; locally on Apple Silicon prefer arm64.
  LambdaArchitecture:
    Type: String
    Default: arm64
    AllowedValues: [arm64, x86_64]

  # Build configuration for the .NET Lambda (SAM build time).
  DotnetBuildConfiguration:
    Type: String
    Default: Release
    AllowedValues: [Debug, Release]
  
  DomainName:
    Type: String
    Default: ""
  
  AllowedOrigin:
    Type: String
    Default: "*"
    Description: Frontend URL for CORS
  
  CognitoUserPoolId:
    Type: String
    Default: ""
    Description: Cognito User Pool ID (from cognito stack or local config)
  
  CognitoClientId:
    Type: String
    Default: ""
    Description: Cognito Client ID (from cognito stack or local config)
  
  CognitoDomain:
    Type: String
    Default: ""
    Description: Cognito Domain (from cognito stack or local config)

  ApexDomain:
    Type: String
    Default: "ttleagueplayers.uk"
    Description: Apex domain name for MX and SPF records

  HostedZoneId:
    Type: String
    Default: ""
    Description: Route 53 Hosted Zone ID for the domain

Globals:
  Function:
    Runtime: dotnet8
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Condition: IsProdOrStaging
    Properties:
      StageName: !Ref Environment
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}"
            IdentitySource: method.request.header.Authorization
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Sub "{{resolve:ssm:/ttleague/${Environment}/certificate-arn}}"
        Condition: HasDomain
      Cors:
        AllowMethods: "'GET,POST,PATCH,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: !Sub "'${AllowedOrigin}'"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: !Sub "'${AllowedOrigin}'"
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Methods: "'GET,POST,PATCH,DELETE,OPTIONS'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: !Sub "'${AllowedOrigin}'"
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Methods: "'GET,POST,PATCH,DELETE,OPTIONS'"

  ApiGatewayFunction:
    Type: AWS::Serverless::Function
    Condition: IsProdOrStaging
    Properties:
      CodeUri: TTLeaguePlayersApp.BackEnd/
      Handler: TTLeaguePlayersApp.BackEnd::TTLeaguePlayersApp.BackEnd.APIGateway.ApiGatewayProxyHandler::Dispatch
      Architectures:
        - !Ref LambdaArchitecture
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:ListUsers
                - cognito-idp:AdminUpdateUserAttributes
              Resource: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*"
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource:
                - !GetAtt InvitesTable.Arn
                - !Sub "${InvitesTable.Arn}/index/*"
                - !GetAtt KudosTable.Arn
                - !Sub "${KudosTable.Arn}/index/*"
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/*"
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:configuration-set/*"
      Events:
        # Public Endpoints (Explicitly override Default Authorizer)
        InvitesRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /invites
            Method: ANY
            Auth:
              Authorizer: NONE
        InvitesRootOptions:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /invites
            Method: OPTIONS
            Auth:
              Authorizer: NONE
        InvitesProxy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /invites/{proxy+}
            Method: ANY
            Auth:
              Authorizer: NONE
        InvitesProxyOptions:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /invites/{proxy+}
            Method: OPTIONS
            Auth:
              Authorizer: NONE
        # Protected Endpoints (Uses Default Authorizer)
        CatchAllProxy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /{proxy+}
            Method: ANY
        # OPTIONS handlers for protected endpoints (bypass auth for CORS preflight)
        KudosOptions:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /kudos
            Method: OPTIONS
            Auth:
              Authorizer: NONE
        KudosStandingsOptions:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /kudos/standings
            Method: OPTIONS
            Auth:
              Authorizer: NONE

  EmailForwarderLambda:
    Type: AWS::Serverless::Function
    Condition: IsProdOrStaging
    Properties:
      CodeUri: TTLeaguePlayersApp.BackEnd/
      Handler: TTLeaguePlayersApp.BackEnd::TTLeaguePlayersApp.BackEnd.Utilities.EmailForwarderLambda::HandleAsync
      Runtime: dotnet8
      Architectures:
        - !Ref LambdaArchitecture
      Policies:
        - S3CrudPolicy:
            BucketName: "ttleague-incoming-emails"
        - SESCrudPolicy:
            IdentityName: "ttleagueplayers.uk"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ses:SendRawEmail
              Resource: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:configuration-set/*"
      Events:
        EmailReceivedEvent:
          Type: S3
          Properties:
            Bucket: !Ref IncomingEmailsBucket
            Events: s3:ObjectCreated:*

  IncomingEmailsBucket:
    Type: AWS::S3::Bucket
    Condition: IsProdOrStaging
    Properties:
      BucketName: "ttleague-incoming-emails"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldEmails
            Status: Enabled
            ExpirationInDays: 7

  IncomingEmailsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: IsProdOrStaging
    Properties:
      Bucket: !Ref IncomingEmailsBucket
      PolicyDocument:
        Statement:
          - Action: s3:PutObject
            Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Resource: !Sub "arn:aws:s3:::${IncomingEmailsBucket}/*"

  SESReceiptRuleSet:
    Type: AWS::SES::ReceiptRuleSet
    Condition: IsProdOrStaging
    Properties:
      RuleSetName: !Sub "ttleague-rules-${Environment}"

  SESReceiptRule:
    Type: AWS::SES::ReceiptRule
    Condition: IsProdOrStaging
    DependsOn: IncomingEmailsBucketPolicy
    Properties:
      RuleSetName: !Ref SESReceiptRuleSet
      Rule:
        Name: "ForwardContactUsToS3AndTriggerLambda"
        Enabled: true
        Recipients:
          - "contact_us@ttleagueplayers.uk"
        Actions:
          - S3Action:
              BucketName: !Ref IncomingEmailsBucket

  SESReceiptRuleInvite:
    Type: AWS::SES::ReceiptRule
    Condition: IsProdOrStaging
    DependsOn: IncomingEmailsBucketPolicy
    Properties:
      RuleSetName: !Ref SESReceiptRuleSet
      Rule:
        Name: "ForwardInviteToS3AndTriggerLambda"
        Enabled: true
        Recipients:
          - "invite@ttleagueplayers.uk"
        Actions:
          - S3Action:
              BucketName: !Ref IncomingEmailsBucket

  MXRecord:
    Type: AWS::Route53::RecordSet
    Condition: IsProdOrStaging
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ApexDomain
      Type: MX
      TTL: 3600
      ResourceRecords:
        - !Sub "10 inbound-smtp.${AWS::Region}.amazonaws.com"

  SPFRecord:
    Type: AWS::Route53::RecordSet
    Condition: IsProdOrStaging
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ApexDomain
      Type: TXT
      TTL: 3600
      ResourceRecords:
        - "\"v=spf1 include:amazonses.com ~all\""
    Metadata:
      BuildProperties:
        Configuration: !Ref DotnetBuildConfiguration

  InvitesTable:
    Type: AWS::DynamoDB::Table
    Condition: IsProdOrStaging
    Properties:
      TableName: !Sub "ttleague-invites-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: nano_id
          AttributeType: S
        - AttributeName: invitee_email_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: N
      KeySchema:
        - AttributeName: nano_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: InviteeEmailIndex
          KeySchema:
            - AttributeName: invitee_email_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - nano_id
              - league
              - season
              - invitee_team
              - invitee_name
              - invited_by
              - accepted_at

  KudosTable:
    Type: AWS::DynamoDB::Table
    Condition: IsProdOrStaging
    Properties:
      TableName: !Sub "ttleague-kudos-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: match_date_time
          AttributeType: N
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: KudosByPlayerIndex
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: match_date_time
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - division
              - receiving_team
              - giver_team
              - giver_person_name
              - kudos_value
        - IndexName: TeamStandingsIndex
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - positive_kudos_count
              - neutral_kudos_count
              - negative_kudos_count

Conditions:
  HasDomain: !Not [!Equals [!Ref DomainName, ""]]
  IsProdOrStaging: !Or [!Equals [!Ref Environment, staging], !Equals [!Ref Environment, prod]]
  HasCognitoParams: !And [!Not [!Equals [!Ref CognitoUserPoolId, ""]], !Not [!Equals [!Ref CognitoClientId, ""]], !Not [!Equals [!Ref CognitoDomain, ""]]]

Outputs:
  ApiUrl:
    Condition: IsProdOrStaging
    Value: !If 
      - HasDomain
      - !Sub "https://${DomainName}"
      - !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
  
  CognitoUserPoolId:
    Value: !If
      - HasCognitoParams
      - !Ref CognitoUserPoolId
      - !ImportValue
        Fn::Sub: "ttleague-cognito-${Environment}-UserPoolId"
  
  CognitoClientId:
    Value: !If
      - HasCognitoParams
      - !Ref CognitoClientId
      - !ImportValue
        Fn::Sub: "ttleague-cognito-${Environment}-ClientId"
  
  CognitoDomain:
    Value: !If
      - HasCognitoParams
      - !Ref CognitoDomain
      - !ImportValue
        Fn::Sub: "ttleague-cognito-${Environment}-Domain"